modules = ["nodejs-20"]

[nix]
channel = "stable-24_05"

[deployment]
run = "npm start"
deploymentTarget = "autoscale"
ignorePorts = false

[[ports]]
localPort = 3000
externalPort = 80

[env]
NODE_ENV = "production"
HOST = "0.0.0.0"
PORT = "3000"
SESSION_SECRET = ""
OPENAI_API_KEY = ""
STRIPE_SECRET_KEY = ""