modules = ["nodejs-20"]

[nix]
channel = "stable-24_05"

[deployment]
run = ["sh", "-c", "npm start"]
deploymentTarget = "autoscale"

[[ports]]
localPort = 3000
externalPort = 80

[env]
NODE_ENV = "production"